<template>
  <div>
    <div class="mb-6 flex items-center justify-between print:hidden">
      <PageHeader title="Invoice" subtitle="Print or save as PDF" />
      <div class="flex gap-2">
        <button @click="printPage" class="btn-primary btn-sm">
          <Printer class="h-4 w-4" /> Print
        </button>
        <router-link to="/admin/billing" class="btn-secondary btn-sm">
          <ArrowLeft class="h-4 w-4" /> Back
        </router-link>
      </div>
    </div>

    <SkeletonLoader v-if="loading" :rows="6" />

    <div v-else-if="inv" class="mx-auto max-w-2xl">
      <div class="card p-8 print:border-0 print:shadow-none">
        <div class="mb-6 flex items-start justify-between border-b border-slate-200 pb-6">
          <div>
            <h1 class="text-xl font-bold text-primary-700">MedFlow HMS</h1>
            <p class="text-sm text-slate-500">Invoice</p>
          </div>
          <div class="text-right">
            <p class="text-xs text-slate-400">Invoice</p>
            <p class="text-sm font-semibold text-slate-900">{{ inv.invoice_number || `#${inv.id}` }}</p>
            <StatusChip :status="inv.status" :label="inv.status" />
          </div>
        </div>

        <div class="mb-6 grid grid-cols-2 gap-4 text-sm">
          <div>
            <p class="text-xs font-semibold uppercase text-slate-400">Patient</p>
            <p class="font-semibold text-slate-900">{{ inv.patient_name || '--' }}</p>
          </div>
          <div>
            <p class="text-xs font-semibold uppercase text-slate-400">Appointment</p>
            <p class="text-slate-700">#{{ inv.appointment_id || '—' }}</p>
          </div>
          <div>
            <p class="text-xs font-semibold uppercase text-slate-400">Issued</p>
            <p class="text-slate-700">{{ inv.issued_at ? formatDateTime(inv.issued_at) : '—' }}</p>
          </div>
          <div>
            <p class="text-xs font-semibold uppercase text-slate-400">Paid</p>
            <p class="text-slate-700">{{ inv.paid_at ? formatDateTime(inv.paid_at) : '—' }}</p>
          </div>
        </div>

        <div class="mb-6 overflow-hidden rounded-xl border border-slate-200">
          <table class="w-full text-sm">
            <thead class="bg-slate-50 text-left text-xs font-bold uppercase tracking-wider text-slate-500">
              <tr>
                <th class="px-4 py-3">Item</th>
                <th class="px-4 py-3 text-right">Qty</th>
                <th class="px-4 py-3 text-right">Unit</th>
                <th class="px-4 py-3 text-right">Total</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="it in inv.items" :key="it.id" class="border-t border-slate-200">
                <td class="px-4 py-3">
                  <p class="font-medium text-slate-900">{{ it.description }}</p>
                  <p class="text-xs text-slate-500">{{ it.item_type }}</p>
                </td>
                <td class="px-4 py-3 text-right text-slate-700">{{ it.quantity }}</td>
                <td class="px-4 py-3 text-right text-slate-700">₹{{ (it.unit_price ?? 0).toFixed(2) }}</td>
                <td class="px-4 py-3 text-right font-semibold text-slate-900">₹{{ (it.total_price ?? 0).toFixed(2) }}</td>
              </tr>
              <tr v-if="!inv.items?.length" class="border-t border-slate-200">
                <td colspan="4" class="px-4 py-6 text-center text-slate-500">No line items</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="grid grid-cols-2 gap-4 text-sm">
          <div>
            <p class="text-xs font-semibold uppercase text-slate-400">Notes</p>
            <p class="text-slate-700">{{ inv.notes || '—' }}</p>
          </div>
          <div class="rounded-xl bg-slate-50 p-4">
            <div class="flex justify-between text-slate-700">
              <span>Subtotal</span><span>₹{{ (inv.subtotal ?? 0).toFixed(2) }}</span>
            </div>
            <div class="mt-1 flex justify-between text-slate-700">
              <span>Tax ({{ inv.tax_percent ?? 0 }}%)</span><span>₹{{ (inv.tax_amount ?? 0).toFixed(2) }}</span>
            </div>
            <div class="mt-1 flex justify-between text-slate-700">
              <span>Discount</span><span>- ₹{{ (inv.discount ?? 0).toFixed(2) }}</span>
            </div>
            <div class="mt-3 flex justify-between border-t border-slate-200 pt-3 text-base font-bold text-slate-900">
              <span>Total</span><span>₹{{ (inv.total ?? 0).toFixed(2) }}</span>
            </div>
          </div>
        </div>

        <div class="mt-8 border-t border-slate-200 pt-4 text-center">
          <p class="text-xs text-slate-400">Generated by MedFlow HMS</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import api from '@/api'
import PageHeader from '@/components/PageHeader.vue'
import SkeletonLoader from '@/components/SkeletonLoader.vue'
import StatusChip from '@/components/StatusChip.vue'
import { ArrowLeft, Printer } from 'lucide-vue-next'

const route = useRoute()
const loading = ref(true)
const inv = ref(null)

function formatDateTime(iso) {
  return new Date(iso).toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })
}

function printPage() {
  window.print()
}

onMounted(async () => {
  const { data } = await api.get(`/admin/invoices/${route.params.id}`)
  inv.value = data
  loading.value = false
})
</script>

